// Generated by CoffeeScript 1.3.3
(function() {

  describe("the backbone elements plugin", function() {
    var View, should;
    should = chai.should();
    View = Backbone.View;
    beforeEach(function() {
      this.clickChildSpy = sinon.spy();
      this.theView = new (View.extend({
        el: $("#test"),
        elements: {
          ".test-child": "child",
          ".test-empty-element": "emptyElement"
        },
        events: {
          "click $child": this.clickChildSpy
        }
      }));
      return this.$child = this.theView.$child();
    });
    describe("the elements attribute", function() {
      it("should be work", function() {
        return this.theView.elements.should.exist;
      });
      return it("should extend elements attribute of view options", function() {
        var newView;
        newView = new View({
          el: $("#test"),
          elements: {
            ".test-child": "child"
          }
        });
        return newView.elements.should.exist;
      });
    });
    describe("the element prefix attribute", function() {
      it("should be work", function() {
        return this.theView.should.have.property(this.theView.elementsPrefix + "child");
      });
      return it("should be a function", function() {
        return this.theView[this.theView.elementsPrefix + "child"].should.be.a("function");
      });
    });
    describe("the select method", function() {
      it("should be work", function() {
        return this.$child[0].should.equal(this.theView.$(".test-child")[0]);
      });
      return it("should return child element when input selector string", function() {
        return this.theView.$child(".test-child-element")[0].should.equal(this.theView.$(".test-child .test-child-element")[0]);
      });
    });
    describe("the select symbol", function() {
      it("should work in events selector", function() {
        this.$child.trigger("click");
        return this.clickChildSpy.called.should.be["true"];
      });
      return it("should work in `this.$` selector", function() {
        return this.theView.$("$child")[0].should.equal(this.theView.$(".test-child")[0]);
      });
    });
    describe("the elementsPrefix attribute", function() {
      return it("should could be changed", function() {
        var newView;
        newView = new View({
          el: $("#test"),
          elementsPrefix: "sym_",
          elements: {
            ".test-child": "child"
          }
        });
        return newView.should.have.property("sym_child").and.that.should.not.have.property("$child");
      });
    });
    describe("the elements cache", function() {
      it("should be work", function() {
        this.theView.$("$child").should.not.equal(this.theView.$("$child"));
        return this.$child.should.equal(this.theView.$child());
      });
      return it("should not cache when element not exist", function() {
        return this.theView.$emptyElement().should.not.equal(this.theView.$emptyElement());
      });
    });
    return describe("the refresh method", function() {
      it("should be work", function() {
        this.theView.refreshElements();
        return this.$child.should.not.equal(this.theView.$child());
      });
      it("should refresh element cache when input true", function() {
        this.$child.should.not.equal(this.theView.$child(true));
        this.theView.$child(true).should.not.equal(this.theView.$child(true));
        return this.theView.$child(true).should.equal(this.theView.$child());
      });
      return it("should refresh events bind when refresh elements cache", function() {
        this.theView.elements = {
          ".test-empty-element": "child"
        };
        this.theView.initElements();
        this.theView.$child().trigger("click");
        return this.clickChildSpy.called.should.be["false"];
      });
    });
  });

}).call(this);
